version: '3.9'

services:
  judgesystem:
    image: ghcr.io/yanorei32/yr32-judgesystem:latest@sha256:aafb0c1937c9e7f8849a6a609212cc9df8f34acb92e830ba2299e7a94be5777e
    hostname: judgesystem
    container_name: judgesystem__judgesystem
    init: true

    restart: unless-stopped
    user: root

    volumes:
      - type: bind
        source: ./practices.json
        target: /etc/practices.json
        read_only: true

      - type: bind
        source: ./users.json
        target: /etc/users.json
        read_only: true

    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M

    networks:
      - judgesystem_cloudflared

  cloudflared:
    image: crazymax/cloudflared:2022.7.1
    hostname: cloudflared
    container_name: judgesystem__cloudflared

    depends_on:
      - judgesystem

    restart: unless-stopped
    user: root

    volumes:
      - type: bind
        source: /etc/cloudflared/cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true

    networks:
      - judgesystem_cloudflared
      - cloudflared_internet

    command:
      tunnel --hostname ${DOMAIN_NAME} --url http://judgesystem:8080

networks:
  judgesystem_cloudflared:
    name: judgesystem__judgesystem_cloudflared
    internal: true

  cloudflared_internet:
    name: judgesystem__judgesystem_internet
