version: '3.9'

services:
  judgesystem:
    image: ghcr.io/yanorei32/yr32-judgesystem:latest@sha256:77d51e3a45c05aa97729d118bb564a4827f06c4f7010342ee9e4d25bc5d565b6
    hostname: judgesystem
    container_name: judgesystem__judgesystem

    restart: unless-stopped
    user: root

    volumes:
      - type: bind
        source: ./practices.json
        target: /etc/practices.json
        read_only: true

      - type: bind
        source: ./users.json
        target: /etc/users.json
        read_only: true

    networks:
      - judgesystem_cloudflared

  cloudflared:
    image: crazymax/cloudflared:2022.5.3
    hostname: cloudflared
    container_name: judgesystem__cloudflared

    depends_on:
      - judgesystem

    restart: unless-stopped
    user: root

    volumes:
      - type: bind
        source: /etc/cloudflared/cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true

    networks:
      - judgesystem_cloudflared
      - cloudflared_internet

    command:
      tunnel --hostname ${DOMAIN_NAME} --url http://judgesystem:8080

networks:
  judgesystem_cloudflared:
    name: judgesystem__judgesystem_cloudflared
    internal: true

  cloudflared_internet:
    name: judgesystem__judgesystem_internet
