version: '3.9'

services:
  judgesystem:
    image: ghcr.io/yanorei32/yr32-judgesystem:latest@sha256:8ab5e0e69efc95ac1ed11e41d28d6b20bbad4053ebd7a8eadeb56f0861b7e79f
    hostname: judgesystem
    container_name: judgesystem__judgesystem
    init: true

    restart: unless-stopped
    user: root

    volumes:
      - type: bind
        source: ./practices.json
        target: /etc/practices.json
        read_only: true

      - type: bind
        source: ./users.json
        target: /etc/users.json
        read_only: true

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

    networks:
      judgesystem_cloudflared:

  cloudflared:
    image: cloudflare/cloudflared:2022.12.1
    hostname: cloudflared
    container_name: judgesystem__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_URL: http://judgesystem:8080
      TUNNEL_HOSTNAME: ${DOMAIN_NAME}
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel
    user: root

    volumes:
      - type: bind
        source: /etc/cloudflared/cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      judgesystem_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - judgesystem__cloudflared

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  judgesystem_cloudflared:
    name: judgesystem__judgesystem_cloudflared
    internal: true

  cloudflared_internet:
    name: judgesystem__judgesystem_internet
